version: '3.8'

services:
  faa-api:
    # 开发环境覆盖设置
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app:cached
      - /app/.venv  # 防止覆盖容器内的虚拟环境
    # 开发态默认直接使用基础 compose 中的 uvicorn --reload 启动